--
-- PostgreSQL database dump
--

-- Baseline schema for EduSchedule (generated from local dev DB)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assignments (
    id bigint NOT NULL,
    class_id bigint,
    subject_id bigint,
    teacher_id bigint
);


--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    grade integer NOT NULL,
    name character varying(10) NOT NULL,
    homeroom_teacher_id bigint
);


--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.slots (
    id bigint NOT NULL,
    day integer,
    period integer,
    assignment_id bigint,
    timetable_id bigint
);


--
-- Name: slots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    periods_grade1 integer,
    periods_grade2 integer,
    periods_grade3 integer,
    periods_grade4 integer,
    periods_grade5 integer,
    short_name character varying(100)
);


--
-- Name: subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_subjects (
    teacher_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    full_name character varying(100) NOT NULL,
    is_active boolean,
    max_periods_per_week integer NOT NULL,
    type character varying(20) NOT NULL,
    CONSTRAINT teachers_type_check CHECK (((type)::text = ANY ((ARRAY['BO_MON'::character varying, 'CHU_NHIEM'::character varying, 'KHAC'::character varying])::text[])))
);


--
-- Name: teachers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timetables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timetables (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    published_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    name character varying(255)
);


--
-- Name: timetables_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.timetables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timetables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    is_first_login boolean,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: slots slots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT slots_pkey PRIMARY KEY (id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);


--
-- Name: teacher_subjects teacher_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT teacher_subjects_pkey PRIMARY KEY (teacher_id, subject_id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: timetables timetables_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timetables
    ADD CONSTRAINT timetables_pkey PRIMARY KEY (id);


--
-- Name: slots ukauj8q1htw671m3iy1ylwd1yg4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT ukauj8q1htw671m3iy1ylwd1yg4 UNIQUE (timetable_id, day, period);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: assignments ukru487t21ufct675i2pbwxprqr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT ukru487t21ufct675i2pbwxprqr UNIQUE (class_id, subject_id, teacher_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: assignments fk15vvra255mh2h6merxffxmb2t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fk15vvra255mh2h6merxffxmb2t FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: teacher_subjects fk6dcl3ihufp4v0j1fuxlw4ksoj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT fk6dcl3ihufp4v0j1fuxlw4ksoj FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: classes fkaxo95v7ah8hpe1ogasiqoxvae; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fkaxo95v7ah8hpe1ogasiqoxvae FOREIGN KEY (homeroom_teacher_id) REFERENCES public.teachers(id);


--
-- Name: teacher_subjects fkdweqkwxroox2u7pbmksehx04i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT fkdweqkwxroox2u7pbmksehx04i FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: slots fkfhiteip8akp0etyoyirqt2h76; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT fkfhiteip8akp0etyoyirqt2h76 FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: assignments fkmd9krpotkeiujbef6ren2yvq5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkmd9krpotkeiujbef6ren2yvq5 FOREIGN KEY (subject_id) REFERENCES public.subjects(id);


--
-- Name: slots fkq7svpiv176mi2decuvgy0wywc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT fkq7svpiv176mi2decuvgy0wywc FOREIGN KEY (timetable_id) REFERENCES public.timetables(id);


--
-- Name: assignments fkthsv5nybgtij6aybrhfb6n6of; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkthsv5nybgtij6aybrhfb6n6of FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Baseline schema complete
--
